# lightning.pytorch==2.1.2
seed_everything: 999
trainer:
  accelerator: cuda
  strategy: ddp_find_unused_parameters_true
  devices: -1
  num_nodes: 1
  precision: bf16
  logger: null
  callbacks: null
  fast_dev_run: false
  max_epochs: null
  min_epochs: null
  max_steps: 10
  min_steps: null
  max_time: null
  limit_train_batches: null
  limit_val_batches: 5
  limit_test_batches: null
  limit_predict_batches: null
  overfit_batches: 0.0
  val_check_interval: 0.25
  check_val_every_n_epoch: 1
  num_sanity_val_steps: 0
  log_every_n_steps: 100
  enable_checkpointing: null
  enable_progress_bar: null
  enable_model_summary: null
  accumulate_grad_batches: 1
  gradient_clip_val: null
  gradient_clip_algorithm: null
  deterministic: null
  benchmark: null
  inference_mode: true
  use_distributed_sampler: true
  profiler: null
  detect_anomaly: false
  barebones: false
  plugins: null
  sync_batchnorm: false
  reload_dataloaders_every_n_epochs: 0
  default_root_dir: null
optimizer:
  lr: 0.0003
  betas:
  - 0.9
  - 0.999
  eps: 1.0e-08
  weight_decay: 0.0
  amsgrad: false
  foreach: null
  maximize: false
  capturable: false
  differentiable: false
  fused: null
checkpoint_metric: val/loss
checkpoint_mode: min
no_wandb: false
notes: null
early_stopping_patience: 10
gradient_log_interval: 0
load_weights_path: null
freeze_encoder: false
run_name: null
pl_seed: 2494
no_ckpt: false
ckpt_path: null
model:
  class_path: src.models.models.LLaVA
  init_args:
    hf_name_or_path: liuhaotian/llava-llama-2-7b-chat-lightning-lora-preview
    model_base: meta-llama/Llama-2-7b-chat-hf
    model_name: null
    encoder_name: matplotlib
    val_bootstraps: 0
    warmup_steps: 10
    batch_size: 1
    compute_metrics: true
    optimizer: torch.optim.Adam
    lr_scheduler:
      class_path: torch.optim.lr_scheduler.ConstantLR
      init_args:
        factor: 1.2
        total_iters: 5
        last_epoch: -1
        verbose: false
    reset_weights_before_fit: false
data:
  class_path: src.models.tasks.MultimodalTask
  init_args:
    ts_column: series
    context_columns:
    - description_tiny
    - metadata
    - question
    label_column: description
    cache_path: data/processed/QA/
    context_prefix: 'Answer the following question about the time series:'
    index_from_options: true
