# lightning.pytorch==2.1.2
trainer:
  accelerator: cuda
  strategy: auto
  devices: -1
  num_nodes: 1
  precision: bf16
  logger: null
  callbacks: null
  fast_dev_run: false
  max_epochs: 10
  min_epochs: 10
  limit_train_batches: 100
  limit_val_batches: 100  
  max_steps: -1
  limit_predict_batches: 0
  val_check_interval: null
  check_val_every_n_epoch: 1
  num_sanity_val_steps: 0
  log_every_n_steps: 50
  reload_dataloaders_every_n_epochs: 1
  default_root_dir: null
model:
  class_path: src.models.models.HFTranscriptionModel
  init_args:
    hf_name_or_path: openai/whisper-large 
    batch_size: 10
optimizer:
  lr: 0.001