class_path: src.models.tasks.MultimodalMCQTask 
init_args:
  num_classes: 4
  ts_column: series
  cache_path: data/processed/qa_gpt4_incorrect
  context_prefix: "Answer the following question about the time series"
  context_columns: ["description_tiny", "metadata", "question"]
  shuffle_labels: False
  format_abc_mcq: True